### ISSUE TITLE
improper deserialized to json form

### ISSUE THREAD

**Issue by aloktech** [owlike/genson#109]
The class is Person as below:
public class Person {
   public String name;
    public int age;
    @JsonProperty(value = "dob")
    @JsonDateFormat(value = "yyyy-MM-dd")
    public Date dateOfBirth;
}
The deserialized value as json is as below:
{
  "age":28,
  "dateOfBirth":1489659098967,
  "dob":"2017-03-16",
  "name":"Foo"
},
where key "dateOfBirth" is unwanted.

**Comment by EugenCepoi** [comment]
I did run a quick and this seems to work fine with latest Genson version.

What version are you using? Do you have full running code that would allow me to reproduce it? Perhaps you have some specific Genson configuration that hits a bug.

**Comment by aloktech** [comment]
@Data
public class Person {

    private String name;
    private int age;
    @JsonProperty(value = "dob")
    @JsonDateFormat(value = "yyyy-MM-dd")
    private Date dateOfBirth;
}

public static void main(String[] args) {
        Genson genson = new GensonBuilder()
                .useDateFormat(new SimpleDateFormat("yyyy-MM-dd"))
                .useIndentation(true)
                .useConstructorWithArguments(true)
                .create();
        
        Person person = new Person();
        person.setAge(10);
        person.setDateOfBirth(new Date());
        person.setName("Alok");
        
        String data = genson.serialize(person);
        System.out.println(data);
    }

Output:
{
  "age":10,
  "dateOfBirth":1501994169818,
  "dob":"2017-08-06",
  "name":"Alok"
}
where "**dateOfBirth**" is unwanted
I have used the maven 1.4 jar

**Comment by aloktech** [comment]
`@Data
public class Person {

    private String name;
    private int age;
    @JsonProperty(value = "dob")
    @JsonDateFormat(value = "yyyy-MM-dd")
    private Date dateOfBirth;
}`
`    public static void main(String[] args) {
        Genson genson = new GensonBuilder()
                .useDateFormat(new SimpleDateFormat("yyyy-MM-dd"))
                .useIndentation(true)
                .useConstructorWithArguments(true)
                .create();
        
        Person person = new Person();
        person.setAge(10);
        person.setDateOfBirth(new Date());
        person.setName("Alok");
        
        String data = genson.serialize(person);
        System.out.println(data);
    }`
Output
{
  "age":10,
  "dateOfBirth":1501994169818,
  "dob":"2017-08-06",
  "name":"Alok"
}
where "**dateOfBirth**" is unwanted.
I have used Maven 1.4 jar

**Comment by EugenCepoi** [comment]
By default Genson is not looking at field annotations. So if you add only JsonDateFormat for example on your property you will see that it is not being used. By adding JsonProperty to a field you tell Genson to include this field as part of ser/de. However you use a different name there from the one that has the getter (dob vs dateOfBirth). So Genson isn't able to match them anymore.

You have a few options:
  - Don't rename to dob, just use @JsonProperty on the field to include it.
  - Disable getter/setter resolution and use only fields: `builder..useFields(true, VisibilityFilter.PRIVATE).useMethods(false)`

Note also that if you want to serialize all your dates as strings using a custom date format instead of millis, you need to disable timestamp serialization: `builder.useDateAsTimestamp(false)`.
In that case you can get rid of JsonDateFormat annotation.
