### ISSUE TITLE
Java 8 time bundle for genson builder 

### ISSUE THREAD

**Issue by sooraj20890** [owlike/genson#116]
Either jsr 310 or java 8 time related bundle is not available right now  for gensonbuilder like it is for jackson..why not ? i am trying to cache java 8 time and its blowing up..i need a bundle...can you guys please provide a solution ?

**Comment by EugenCepoi** [comment]
Closing, same as https://github.com/owlike/genson/issues/33.

It's not present because I don't have the time to add them, but all contributions are welcome, so if you wanted to create a new bundle with these types that would be great. You can even have it as a separate project and we could reference it in Genson. Thank you.
