### ISSUE TITLE
Extend JAX-RS en/disabling support to RestEasy

### ISSUE THREAD

**Issue by ragnarokkrr** [owlike/genson#42]
Hi,

I'm aware of a similar issue (#39) that implements disabling JAX-RS for Jersey implementation.

I think that the appeal for genson addition to an existing app is the smoother control on serialization, specially  in case of migration from JAXB format to a cleaner alternative. We are facing this problem with jettison JAXB implementation that seems to be quite restrictive.

Said that, I figured out that this feature (#39) is constrained to Jersey application.  Would it be possible to do such JAX-RS switching mechanism to ReastEasy implementation? 

I tried to hack from the source but just achieved success by removing the `META-INF/service` folder  declared hooks from the final JAR.

Do you know an alternative to switch genson  on/of in Resteasy? If you have an idea, an you agree, I could implement it and submit a patch.

Thank you!

**Comment by EugenCepoi** [comment]
Hey,

You want to switch from jettison to genson (or maybe have both at same time) and need to be able to disable Genson from being registered with RestEasy right?

On what version of jax-rs and resteasy are you? This fix indeed is for jersey (impl of JAX-RS 2+) specific.
I will try some stuff and once I have an idea of how it can be done I will share it with you and let you implement the fix.

Thanks

**Comment by ragnarokkrr** [comment]
I've implemented a Json-rpc (http://json-rpc.org/) proxying client for my employee using Spring AOP, http-commons and genson to access a proprietary Json-rpc API from one of our suppliers. Genson just solved the serialization issues like a charm. Absolutely zero problems, mainly in Collections deserialization.

But I had to deploy it with jettison in our application (which is pervasive). In this integrated env I tried several switches and filters in RestEasy configuration but didn't get to make it stop to scan genson.

Besides genson performance, replace it would be awful, once the alternatives (gson, jackson, jettison...) or don't share genson scope or else have cumbersome/sloppy API.

We are using Resteasy 3.0.8 which implements JAX-RS 2+.

Thank you

**Comment by EugenCepoi** [comment]
I didn't have the time to test it yet, but I think I know how it could be achieved.

Declare in GensonJsonConverter some public config string "jaxrs.genson.disable".
We could use @Context to inject Application into GensonJsonConverter [here](https://github.com/owlike/genson/blob/c69218c3ad7d6169e94c8b821e591dc7f7997613/genson/src/main/java/com/owlike/genson/ext/jaxrs/GensonJsonConverter.java#L53). Then get from it the value of property "jaxrs.genson.disable". If missing or false then set a boolean flag to enabled otherwise false.

Then update the isReadable/Writable to check this flag.

Would be great if you could also update JerseyAutoDiscoverable to use the same property instead of jersey.genson.disable.

Let me know if you want to code it or encounter any problems doing it.

Thank you! :)

**Comment by ragnarokkrr** [comment]
Great!!!

I'll take a look on this tonight!

see ya!

**Comment by ragnarokkrr** [comment]
Hello, Eugen!

I diverged a little bit from  your proposal. Let's see it you find it ok.

Unfortunately I couldn't reach  an injected **Application** instance from Resteasy trough **@Context** annotation. Neither in a run from **ClientBuilder**, nor from a run via **DispatcherServlet**. Instead of **Application** I used an injected **ServletConfig** instance, that will be there just in a Web Container run.

I didn't make a pull request yet just to see if you have any objection or recommendation regarding this patch. You could see it [here](https://github.com/ragnarokkrr/genson/commit/146b799458d05a19001a936078883811d7e66fc5).

**Comment by EugenCepoi** [comment]
Hey there,

It looks like I have missed a major class javax.ws.rs.core.Configuration.
Try to inject it instead of Application and then extract the property from there.
I tried injecting it and it looks like it works.

The problem with ServletConfig is that people using only the client (might even happen for the server - depending on the impl) will not necessarilly be running in a "web context" and have the classes from javax.servlet.

Thanks!

**Comment by EugenCepoi** [comment]
I remember now. Downside is that Configuration exists only in jaxrs 2...
Thats why I was thinking of using Application as it exists in both versions.
This is a problem as I want to keep the same Genson package work with both versions.
It makes things much easier for the end users of the lib.

Other solutions I see:
 1) Use some system property to disable Genson. I don't like it, if users want to test code with Genson disabled it will be painfull to set this property.

 2) Use a contextresolver that returns a null genson instance and use it as a flag to disable it in isReadable/Writable. We could make GensonStandardResolver class public and its constructor take a flag to return a null instance. People would then only have to register it with the flag to disabled. . Ugly to use null to check it but easier to impl and use.

 3) Another hack around ContextResolver. The idea would be to have a class (JAXRSConfig or any better name) that holds some configs (disabled etc) related to jax-rs + a genson instance and a contextresolver that provides instances of this. We could use the ContextResolver as a kind of builder like:
GensonContextResolver ctxResolver = new GensonContextResolverBuilder()
  .disable(true)
  .use(new Genson())
  .create();

Then register this instance in the app/client. Internally the create method would create an instance of GensonContextResolver, JAXRSConfig (both immutable) and tie them together. In the converter you would then use this JAXRSConfig instead of getting directly the genson instance from the resolver.
This solution could provide greater flexibility and reduce user code when they want to provide a custom Genson instance. But is more work.

Solution 2 and 3 are maybe not so good if people don't configure the app programmatically (web.xml ?), but is it really the case in practice?

What is your opinion? Let me know if my explanations are unclear :)

Thank you :)

**Comment by ragnarokkrr** [comment]
I got your preoccupation on backwards compatibility.... I'll take a careful look on your points at night....

see ya!

**Comment by EugenCepoi** [comment]
@ragnarokkrr Do you plan working on it? I'd like to make a new release soon and integrate this new fix. If you don't have the time I'll have a look at it.
Thanks!

**Comment by ragnarokkrr** [comment]
Hi Eugen,

sorry for the late in answering you. Unfortunately for the last weeks I've
got sick and had to stop almost all my activities, including professional.

I came back last week. I'm 100% better now and I'm resuming my backlog.
Regarding genson, I'm interested in contribute!

If It would not hold back your schedule, I could take the activity by the
next monday. If don't

Could that be?

Thanks!

On Mon, Mar 9, 2015 at 2:41 PM, Eugen Cepoi <notifications@github.com>
wrote:

> @ragnarokkrr <https://github.com/ragnarokkrr> Do you plan working on it?
> I'd like to make a new release soon and integrate this new fix. If you
> don't have the time I'll have a look at it.
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/owlike/genson/issues/42#issuecomment-77903909>.
>



-- 

Nilseu Padilha
Software Architect

Assistant Professor - FAQI

Sciences Reasearch Nucleus - FAQI

MSc. in Computer Science - PUCRS


ragnarokkrr@gmail.com

http://ragnarokkrr.tumblr.com/
http://www.linkedin.com/in/nilseupadilha
http://twitter.com/ragnarokkrr

**Comment by EugenCepoi** [comment]
Hey @ragnarokkrr,

No problem, I just wanted to know if I should wait for you or not.
Hope you are feeling better now! :)

If you want to work on Genson it's great! Genson needs contributors, so any kind of help is very welcome.
About the schedule don't worry, I might do a release without this feature and make another one once it is ready.

**Comment by ragnarokkrr** [comment]
Hi Eugen,

Today I'll resume the issue, so I'll have news by next couple days...

**Comment by ragnarokkrr** [comment]
Hi, Eugen,

regarding the third alternative,I think that it  could decouple de parametization from genson instantiation. And your concern about web.xml we could use an implementation of javax.servlet.ServletContextListener that sets up a JAXRSConfig. A little bit like spring's application context startup. I will try to use @Context to inject javax.servlet.ServletContext in GensonJsonConverter to switch Provider instantiation on or off.  

What do you think?

**Comment by EugenCepoi** [comment]
GensonJsonConverter is supposed to be used on both server and client side. On client side people can use it with jersey client that does not require servlet api. So we can not use javax.servlet classes as they will not be necessarily present at runtime.

Do you think people are usually configuring JAXRS apps through web.xml or programmatically?
My guess is that they do it programmatically (and if they don't we can still ask them to do so as it is relatively easy). I think that the API should be completely independent from servlet and cie.

Lets go with a first shot at 3) and then iterate on it.
