### ISSUE TITLE
Genson JaxbBundle not utilizing XmlJavaTypeAdapter properly

### ISSUE THREAD

**Issue by jessecrossley** [owlike/genson#46]
Genson chokes when trying to write out my `java.util.Calendar` dates because the `JaxbBeanPropertyFactory.getType()` method doesn't check to see if the AccessibleObject has an XmlJavaTypeAdapter in order to ensure that the XmlElement type will be assignable.  The method works if we simply check that the annotation is non-null:

    private Type getType(AccessibleObject object, Type objectType, Type contextType) {
      XmlElement el = object.getAnnotation(XmlElement.class);
      if (el != null && el.type() != XmlElement.DEFAULT.class) {
        if (!TypeUtil.getRawClass(objectType).isAssignableFrom(el.type())) {
            XmlJavaTypeAdapter ad = object.getAnnotation(XmlJavaTypeAdapter.class);
            if (ad == null) 
              throw new ClassCastException("Inavlid XmlElement annotation, " + objectType
                + " is not assignable from " + el.type());
        }
        return el.type();
      } else
        return null;
    }

Once that works, then we find that the `XmlTypeAdapterFactory.create()` method uses the wrong parameter in the match() call...rather than compare the propertyType to the originalType, it should compare it to the adaptedType instead:

    if (!match(propertyType, adaptedType, false))

Of course, the JaxbAnnotationsSupportTest breaks, but I suspect this might be due to the XmlJavaTypeAdapterBean's `public int v` only having an XmlJavaTypeAdapter annotation and no XmlElement annotation (both would be generated by JAX-B).

**Comment by EugenCepoi** [comment]
Can you please provide an example to reproduce it (the class being ser/de)?

**Comment by jessecrossley** [comment]
Yes, I will create a minimal example based on my Jersey-JAXB-JPA-Genson test harness.

**Comment by EugenCepoi** [comment]
Note that you say that *"both would be generated by JAX-B"*, I don't want to force people who don't use generated classes to put both annotations. It is specific to the generator you use.

About *"Once that works, then we find that the XmlTypeAdapterFactory.create() method uses the wrong parameter in the match() call...rather than compare the propertyType to the originalType, it should compare it to the adaptedType instead"*

An xml adapter follows this defintion XmlAdapter<AdaptedType, OriginalType> where OriginalType is the type of your property (or a super type) and adapted type, is the type produced after applying marshal methds on original type. Right?

match(propertyType, originalType, false) is checking that the Original type is assignable from property type. Why do you think it is wrong?

Still there is probably a problem somewhere, the example will be great to debug it.

Thank you for reporting those problems! :)

**Comment by jessecrossley** [comment]
I work from the schema-first standpoint, so I like to use generation to create beans, so all of my Genson usage will be generated-bean specific.  I am, in fact, not well-versed on adding JAXB annotations by hand, so perhaps we can work out the test case issue together.
I will debug further, but it seems to me that the point of using the XmlJavaTypeAdapter is to transform from one type to another and those types probably won't be assignable.  One of my generated fields is "created", an xsd:dateTime mapped to java.util.Calendar.  The xjc-generated and annotated field looks like this:

    @XmlElement(name = "Created", required = true, type = String.class)
    @XmlJavaTypeAdapter(DateAdapter.class)
    @XmlSchemaType(name = "dateTime")
    protected Calendar created;

The DateAdapter is an `XmlAdapter<String, Calendar>`, so here the XmlElement indicates that the original type was a String; the XmlJavaTypeAdapter indicates the original type was String and the adapted type is Calendar; and the declaration indicates the property type is Calendar.  Based on that, I don't see how the match(propertyType, originalType) ever could have worked out...our propertyType shouldn't be assignable from our originalType: it's being adapted!  Maybe the match is unnecessary?  Or, as I originally posited, we only need to ensure that the field's property type matches the adapter's adapted type.

I might not be explaining myself well as I still have just a passing understanding of Genson and I've been at this for quite some time.  I appreciate you bearing with me and taking a look at things.  I will get that test harness ready soon.

**Comment by EugenCepoi** [comment]
*"XmlJavaTypeAdapter is to transform from one type to another and those types probably won't be assignable"*

Yes, but you are mixing the order. The second type in XmlAdapter is supposed to match to your property type. And it does, the match test is correct it compares the that the second type of XmlAdapter (Calendar) matches the type of our property (Calendar too).
To better understand here is what happens: XmlAdapter marshal method is called during serialization. It takes as input your object that has the type of property (Calendar) and transforms it to another type Jaxb knows how to serialize (a String).


About our problem now. XmlElement from my understanding should not have type=String, but type=Calendar or GregorianCalendar or something like that. It is supposed to by a sub type of Calendar.
This makes me think that the tool you use to generate the classes does it wrong or you schema is wrong.
I have found [this question on SO](http://stackoverflow.com/questions/15936368/jaxb-bindings-file-sets-xmlelement-type-to-string-instead-of-xmlgregoriancalend) that seems to be your exact problem. Please have a look at it and check if it works.

**Comment by jessecrossley** [comment]
I tried injecting the XmlElement with type=Calendar early on in debugging...this broke the JPA-aspect of the generated beans and prevented xsd:dateTimes from being serialized properly and stored in the database.  It's true that I am using hyperjaxb3 with xjc, but I have used hj3 successfully for years.  Of course, I have found bugs in that tool, too, so I can investigate there as well.

The SO question's answer is something I'm already doing: using xjb's globalBindings to specify the usage of the DateAdapter:

    <xjc:javaType 
      name="java.util.Calendar"
      xmlType="xs:dateTime"
      adapter="com.mypackage.DateAdapter" />

I left off yesterday with the simplified test almost complete: I am cleaning up the classpath (removing extra dependencies) and I will see how it works without hj3 involved.  I should have it ready in a few hours.

**Comment by EugenCepoi** [comment]
Hum but it seems wrong to have type=String in the generated XmlElement. I think the tool that generates the class has a bug and misunderstood the order between the params in XmlAdapter.
Please try to see if there is a way to not generate a type in XmlElement or use there the right type. If there is no way to do it I can provide a config in Genson to ignore the type from XmlElement. Though I would prefer avoiding that as I really think that the generated code is wrong - or at least it is not how it is supposed to work in standard Jaxb.

Which one of the tools above is the one that generates the classes?

**Comment by jessecrossley** [comment]
I'm using the org.jvnet.jaxb2.maven2:maven-jaxb2-plugin (which uses xjc) to generate.  My simplified simple test harness is no longer using hyperjaxb3 (I've removed JPA from the equation).  My generated bean still contains the XmlElement with type=String, so I'm inclined to believe it is a necessary annotation when XmlJavaTypeAdapter is used.

I'm looking at the XmlAdapter.class source...I think Genson has the order backwards.  The declaration of the class is `public abstract class XmlAdapter<ValueType,BoundType>`, and from the javadoc:

    @param <BoundType>
      The type that JAXB doesn't know how to handle. An adapter is written
      to allow this type to be used as an in-memory representation through
      the <tt>ValueType</tt>.
    @param <ValueType>
      The type that JAXB knows how to handle out of the box.

In my case, the ValueType is String, and my BoundType is Calendar.  But from Genson's `JaxbBundle.XmlTypeAdapterFactory.create()`:

        Type adaptedType = typeOf(0, adapterExpandedType);
        Type originalType = typeOf(1, adapterExpandedType);

From the description of XmlAdapter, originalType should be index=0 and adaptedType should be index=1.  I have a debug statement that bears this out, `log.debug("adaptedType: "+adaptedType+", originalType: "+originalType+", propertyType: "+propertyType);` is spitting out `adaptedType: class java.lang.String, originalType: class java.util.Calendar, propertyType: class java.lang.String`, which is backwards for my DateAdapater<String, Calendar>!

Previously, I incorrectly stated that the propertyType was Calendar, but the logging shows that it is understood to be String (the field is declared as Calendar, but perhaps the XmlElement(type=String) is correctly overriding that?).

**Comment by jessecrossley** [comment]
Ha! When I make that switch, though, my DateAdapter is no longer used by Genson, and it falls through to the default CalendarConverter!  Man, there's a lot going on here...

**Comment by jessecrossley** [comment]
Okay, I think that happens because of the later block of code creating the AdaptedConverter...The XmlAdapter is needed to adapt from the boundType back to the valueType, which then might need a Genson converter to serialize the valueType into JSON.  However, the current code is trying to use the adaptedType to find a Genson converter.  With the following mods, my use case works:

        Type originalType = typeOf(0, adapterExpandedType);
        Type adaptedType = typeOf(1, adapterExpandedType);
        Type propertyType = property.getType();

        if (getRawClass(propertyType).isPrimitive()) 
          propertyType = wrap(getRawClass(propertyType));
        // checking type consistency
        if (!match(propertyType, originalType, false))
          throw new ClassCastException("The BoundType of XMLAdapter " + adapterClass
            + " is not assignable from property " + property.getName()
            + " declared in " + property.getDeclaringClass());

        try {
          XmlAdapter<Object, Object> adapter = adapterClass.newInstance();
          // we also need to find a converter for the original type
          Converter<Object> originalTypeConverter = genson.provideConverter(originalType);
          converter = new AdaptedConverter(adapter, originalTypeConverter);

By adding XmlElement(type=String.class) also gets the test case to succeed, which makes sense to me:  XmlElement(type) tells JAXB what class is used to marshal/unmarshal with while XmlJavaTypeAdapter tells JAXB how to get from that class to our bound class.  In the test case, JAXB and Genson are never told that `public int v` will be serialized as a String, just that there's an adapter to go from String to Integer.  If you want it to work without an XmlElement, then the XmlJavaTypeAdapter ValueType must take precedence over the declared `int` type, because that's the type that will actually be used for Genson serialization later on.

 I've uploaded my test project here: https://drive.google.com/file/d/0B1--msN1wUXFQzBmZ2lmOTZzaG8/view?usp=sharing
You should only need to change the v.genson property to 1.3-SNAPSHOT or your current version.

**Comment by EugenCepoi** [comment]
Ok we were using inverted terminology. I was calling adapted type (ValueType) the one that is the result of a call to adapter.marshal and its input the original type (BoundedType). 

Thanks for your test case, I can see better what the problem is and think about it.

I don't see in the JAXB spec that XmlTypeAdapter and XmlElement should be used together, so I assume they don't. Using them together is an option.


**Trying to understand the spec**

If they are not used together we should not compare the propertyType (Calendar) to originalType (String) as they will never be the same. Thus we can not use this fix `if (!match(propertyType, originalType, false))`.

Now lets look at the case when they are being used together as it is when the problem happens.
If the type in XmlType was some class in the same hierarchy as the propertyType, then it would be useless, right? As we already have the type information in the adapter signautre.

This means that the only point when combining those annotations together is to define a type X in XmlElement that is in the same class hiearchy as the ValueType Y of the adapter. This type X would be then used during serialization. Do you agree with this logic?

**How to solve the problem**
If yes here is what I propose:
 - If there is an XmlAdapter+XmlElement, during property type resolution ignore the type from XmlElement (done in the method you showed previously `private Type getType(AccessibleObject object, Type objectType, Type contextType)`). Otherwise keep the same logic as now, use the type from XmlElement if defined.

 - In the create method, don't change the match logic, but if the beanProperty has also an XmlElement annotation with type (say X) defined in there then extract that type (beanProperty has a getAnnotation method). Do a type safety check (match) between the ValueType of the adapter and X (I don't know if we should check that ValueType is assignable from X, the inverse or check if one or the other is true). If the check fails then throw a ClassCastException like the other match check, otherwise use type X to obtain a Converter: `genson.provideConverter(typeX)`.


What do you think about this? If this works for you and would like to provide the fix via a pull request it is super welcome. Otherwise I will do it.

Thanks!

**Comment by jessecrossley** [comment]
Tried and tested and it seems successful: my use case works as do your test cases, so that's a win, right? Very thoroughly regression tested, I must say...Hopefully we caught an outlier case, though, because I'm about to make extensive usage of this jersey-based JAXB-JPA-Genson framework.  It's amazing how little code I've had to write even to get this far; I just needed to sharpen some of the tools a bit.

I'll make a pull request (there's a first time for everything).  If for whatever reason I cannot, then I'll post my edits here.
