### ISSUE TITLE
Generated from XSD, how to set @JsonProperty

### ISSUE THREAD

**Issue by jiechu** [owlike/genson#74]
I have a XSD, like:
`<xs:complexType name="property">`
`<xs:attribute name="key" type="xs:string" use="required"/>`
`<xs:attribute name="value" type="xs:string" use="required"/>`
`</xs:complexType>`
And the binding.xjb like:
`<jxb:bindings node="xs:complexType[@name='property']">`
`<annox:annotate>`
`<annox:annotate annox:class="javax.xml.bind.annotation.XmlRootElement" name="property"/>`
`</annox:annotate>`
`</jxb:bindings>`
`<jxb:bindings node="xs:complexType[@name='property']/xs:attribute[@name='key']">`
`<annox:annotate target="field">@com.owlike.genson.annotation.JsonProperty(value="@key")</annox:annotate>`
`</jxb:bindings>`
`<jxb:bindings node="xs:complexType[@name='property']/xs:attribute[@name='value']">`
`<annox:annotate target="field">@com.owlike.genson.annotation.JsonProperty(value="@value")</annox:annotate>`
`</jxb:bindings>`

But when test with the generated Property.java, it print as:
`{`
`    "@key":"tKey",`
`    "@value":"tValue",`
`    "key":"tKey",`
`    "value":"tValue"`
`}`

I just want "@key" and "@value", not "key" nor "value".
How to solve this issue?

**Comment by EugenCepoi** [comment]
Configure Genson to use only fields and it should work.

**Comment by jiechu** [comment]
But it is a jersey restful webservice. I use automatically register. Does not have a chance to configure Genson.
Could you please give a  comments or a snippet how to resolve?

**Comment by EugenCepoi** [comment]
You can provide a custom configured instance of Genson to Jersey, have a look at [the documentation here](http://owlike.github.io/genson/Documentation/Extensions/#jax-rs-jersey--cie).

**Comment by jiechu** [comment]
Thanks Eugen.
The solution is as: 
Genson genson = new GensonBuilder().withBundle(new JodaTimeBundle())
                .withBundle(new JAXBBundle())
                .withBundle(new JSR353Bundle())
                .usePermissiveParsing(true)
                .useIndentation(true)
                .useRuntimeType(true)
                .create();
clientConfig.register(new GensonJaxRSFeature().use(genson));
builtClient = ClientBuilder.newBuilder().withConfig(clientConfig).build();

I use this to implement openfire client in json message. Openfire always send single value as array.
It is better to use explicit SINGLE_VALUE_AS_ARRAY instead of usePermissiveParsing(true). :)

**Comment by EugenCepoi** [comment]
Great, I am glad it works for you.
What do you mean by __*use explicit SINGLE_VALUE_AS_ARRAY instead of usePermissiveParsing(true)*__? You mean that it would be better to have a separate option to enable this feature instead of mixing things with usePermissiveParsing?
Originally I was thinking of having that, but after a discution with someone I choosed to group stuff. But now I indeed think it would be better to separate things...well I guess it is human to change our mind :)

**Comment by jiechu** [comment]
That SINGLE_VALUE_AS_ARRAY comes from Jackson 2.x. Some configuration in Jackson is more understandable. 
BTW, when can Genson support JAXB XmlType order?

**Comment by EugenCepoi** [comment]
Can you please list the configs that are unclear in Genson (and what you would expect), so I can try to improve the names.

Concerning XmlType I don't have any plans yet (mostly due to lack of time, favoring other features, no one asked for it). If you need this feature, the best would be to contribute it. I can help you if you are interested in adding support for XmlType.

Thanks for the feedback!
